GET https://express-lvqj.vercel.app/nilai
###
POST https://express-lvqj.vercel.app/nilai
Content-Type: application/json
{
  "nama": "Budi",
  "kelas": "XII",
  "nh1": 90,
  "nh2": 80,
  "nh3": 70,
  "uts": 50,
  "uas": 60,
  "nilai_akhir": 90,
}
###
GET https://express-gules-nine.vercel.app/nilai
###
POST https://express-gules-nine.vercel.app/nilai